apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mymariadb
  name: mymariadb
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mymariadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mymariadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        resources: {}
status: {}
